### ISSUE TITLE
[Error on forking the project]

### ISSUE THREAD

**Issue by sidduprecious** [Psiservices-Jagannatha/KarateExtentReport#1]
@Psiservices-Jagannatha 
<img width="937" alt="error_extentreports" src="https://user-images.githubusercontent.com/41496589/168225270-ca179627-62b0-4ef5-b745-da8e89b2595a.png">

Forked your project repo to eclipse, & tried to generate extent reports using runner class,getting the error as attached in screenshots

please provide solution for that error

**Comment by Psiservices-Jagannatha** [comment]
Hi Siddu,
The issues are fixed in the new repository and you can find the repository details in the below link.
https://github.com/Psiservices-Jagannatha/KarateExtentIntegration

it will resolve your issues.
